In [11]:
print('Hello, world!')


Hello, world!


## 数式
$$y = \int^t_0 f(\tau)\rm{d}\tau$$

このように数式が書かれます。


In [12]:
help(print)


Help on built-in function print in module builtins:

print(...)
    print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)
    
    Prints the values to a stream, or to sys.stdout by default.
    Optional keyword arguments:
    file:  a file-like object (stream); defaults to the current sys.stdout.
    sep:   string inserted between values, default a space.
    end:   string appended after the last value, default a newline.
    flush: whether to forcibly flush the stream.



In [13]:
print?


In [14]:
# コメントです
print(1)


1


In [18]:
'''
コメント1
コメント2
'''

x = 1

print(x)

x

1


1

In [20]:
print(type(x))


<class 'int'>


In [21]:
y = 1.0
msg = 'Control'
ok = True


In [23]:
z = int(y)
word = str(x)


In [25]:
data1 = [3, 5, 2, 4, 6, 1]

In [28]:
data2 = [[3, 5, 2], [4, 6, 2]]


In [30]:
data1[0:2]

[3, 5]

In [33]:
data1[2:4]


[2, 4]

In [35]:
data1.append(8)
print(data1)

[3, 5, 2, 4, 6, 1, 8, 8]


In [36]:
data1.insert(0, 8)
print(data1)

[8, 3, 5, 2, 4, 6, 1, 8, 8]


In [37]:
del data1[0]

In [38]:
data1.pop(0)


3

In [39]:
x = [1, 2, 3]
y = x
y[0] = 10
print(x)
print(y)

[10, 2, 3]
[10, 2, 3]


In [40]:

x = [1, 2, 3]
y = x.copy()
y[0] = 10
print(x)
print(y)

[1, 2, 3]
[10, 2, 3]


In [41]:
tuple = (1, 2, 3, 4)
type(tuple)


tuple

In [42]:
d = {'linestyle': '-.', 'color': 'k'}
print(d)
print(d['linestyle'])
print(d['color'])

{'linestyle': '-.', 'color': 'k'}
-.
k


In [43]:
x = {'linestyle': '--', 'label': 'plt'}
d.update(x)
print(d)


{'linestyle': '--', 'color': 'k', 'label': 'plt'}


In [44]:
x = 0
if x < 0:
    print('x is negative')
elif x == 0:
    print('x is zero')
else:
    print('x is positive')


x is zero


In [45]:
x = -1; y = -2
if x < 0 and y < 0:
    print('x and y are negative')


x and y are negative


In [46]:
from numpy import sqrt
s = 0
for x in range(1, 51):
    s += x
print(sqrt(s))

s = sum(range(1, 51))
print(sqrt(s))

s = sum(x for x in range(1, 51))
print(sqrt(s))

35.70714214271425
35.70714214271425
35.70714214271425


In [1]:
import numpy as np

In [2]:
A = np.array([[1, 2], [-3, 4]])
print(A)


[[ 1  2]
 [-3  4]]


In [3]:
print(A.T)

[[ 1 -3]
 [ 2  4]]


In [4]:
B = np.linalg.inv(A)
print(B)


[[ 0.4 -0.2]
 [ 0.3  0.1]]


In [5]:
np.linalg.det(A)

10.000000000000002

In [6]:
np.linalg.matrix_rank(A)

2

In [7]:
w, v = np.linalg.eig(A)
print('eigenvalue=', w)
print('eigenvector=\n', v)

eigenvalue= [2.5+1.93649167j 2.5-1.93649167j]
eigenvector=
 [[0.38729833-0.5j 0.38729833+0.5j]
 [0.77459667+0.j  0.77459667-0.j ]]


In [8]:
x = np.array([1, 2])
print(x)
np.linalg.norm(x)

[1 2]


2.23606797749979

In [10]:
Td = np.arange(0, 10, 1)
print(Td)

[0 1 2 3 4 5 6 7 8 9]
